### ISSUE TITLE
US3 - add ingredients to Recipe

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#11]
## Value proposition
As a user
I want to add all needed ingredients to a new recipes
In order to have them clearly listed.

## Description

<img width="694" alt="Bildschirm­foto 2023-10-23 um 09 48 15" src="https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/f3f39627-b48b-4398-b897-e7a0540d70c6">

## Acceptance criteria
- [ ] Component "FormularAddIngredients"
- [ ] Input-Field for ingredient itself (required)
- [ ] Input-Field for amout (number, required)
- [ ] Input-Field for unit (dropdown, not required)
- [ ] Button "+" that adds new ingredient to list
- [ ] All added ingredients are displayed
- [ ] Component is displayed in Formular "FormularAddRecipe" (US2)

## Tasks
- [ ] create new branch "US3-FormularAddIngredients"
- [ ] create new Component "FormularAddIngredients"
- [ ] Input-Fields for Ingredient, Amount and Unit
- [ ] Submit-Button "+" that adds ingredient to list
- [ ] Container that displays all added ingredients
- [ ] rendering "FormularAddIngredients" inside of Component "FormularAddRecipe"

**Comment by PeetThesing** [comment]
Hi!
We have some small remarks: In your Wireframe you have the heading "add ingredients" which looks like a button, but in the acceptance criteria it's not listed which functionality it should have. Maybe specify in the acceptance criteria (& if necessary the wireframe) if you want to display a heading or a button.

Another point: The developer tasks shouldn't be in the acceptance criteria, only the view of the user.
Move "Component "FormularAddIngredients"to the task section and remove  "Component is displayed in Formular "FormularAddRecipe" (US2)"  because it is already in the task section. 
As the first acceptance criterion write something like "Within the new recipe form there is a subsection to add ingredients".

Kind regards.

**Comment by PeetThesing** [comment]
Perfect!
