### ISSUE TITLE
US4- Delete Ingredients

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#12]
## Value proposition
As a user 
I want to be able to delete ingredients
In order to correct mistakes.

## Description
<img width="290" alt="Bildschirm­foto 2023-10-23 um 19 38 04" src="https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/62a8115b-6a09-4461-93cc-fa7e948bc0ae">

## Acceptance criteria
- [ ] a Button "X" next to each ingredient is displayed
- [ ] when submitting the button, the chosen ingredient will be deleted from the list
- [ ] after deleting, the focus is set in the ingredients-field

## Tasks
- [ ] new Branch "US4-DeleteButton"
- [ ] new Component "DeleteButton"
- [ ] styled Component: small button with red "X"
- [ ] positioned at top right corner of each ingredient
- [ ] event listener for button, that deletes item
- [ ] implement Method Delete for Database
- [ ] set focus in input-field "ingredient"

**Comment by julialoeschel** [comment]
Hey there. 
good story. 

I suggest to rephrase the sentence `when submitting the button, the chosen ingredient will be deleted from the list`. 
be button in not in a form (as far as I see), so you are not submitting anything. 
maybe just clicking would be the better word. 

🐜

**Comment by gwittm** [comment]
Hey Julia! Thanks for your comment. It is a form (we implemented it in US3), but i changed the word :)

**Comment by FelineHuhn** [comment]
LGTM 🚀
