### ISSUE TITLE
US5 - DetailsPage

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#14]
## Value proposition
As a user
I want to  have a details page for each recipe
In order to see all information about it.

## Description
![Bildschirm­foto 2023-10-25 um 12 45 13](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/1bdfeb1c-0d13-4988-82af-11e522b79ecb)

## Acceptance criteria
- [ ] a dynamic details page for each recipe 
- [ ] that shows a heading (dynamic; title of the recipe)
- [ ] sections on top: type, needed time, amount of servings
- [ ] section ingredients
- [ ] section preparation
- [ ] a Button, that redirects to starting page

## Tasks
- [ ] new branch "US5-detailsPage"
- [ ] Component Recipe
- [ ] dynamic routing
- [ ] Recipe displays heading and all sections
- [ ] styled sections display flex
- [ ] Link-Component (visible as button), that redirects to starting page

**Comment by FelineHuhn** [comment]
Very nice user story 🙌 And I love the app idea!

I have two general suggestions: You could be a bit more detailed in your acceptance criteria and also tasks.

To give you an example for the acceptance criteria - Instead of the short acceptance criteria: "section ingredients", "section preparation", (...) you could write more descriptive criteria, which would explain more, what the user should see: 

- [ ] The details page should be divided into sections: 
   - [ ] An overview section displaying the recipe type, preparation time, and serving size
   - [ ] An ingredients section listing all necessary ingredients for the recipe
   - [ ] A preparation section guiding through the cooking process
 
Just to give you another example for a more descriptive task - instead of "Component Recipe" you could better write "create a component `Recipe`"

This is a general device for all future user stories, so you don't have to adjust it in this user story, but maybe enhances your future user stories. 

The reason for giving you not the green check for now is, that in the wireframe + acceptance criteria + tasks is missing the starting point of your feature, or? From where does the user get to the details page? You should show this in the wireframe and also mention it in the acceptance criteria and tasks, since the feature will not be accessible to the user without a link somewhere, or?

**Comment by gwittm** [comment]
Thank you for your helpful comments! We changed our US accordingly :)

**Comment by NikRoe** [comment]
Well done 👏

**Comment by gwittm** [comment]
Hi All, we just noticed that we forgot to mention one section.
The following sections will be displayed in the overview section: type, preparation time, amount of servings, preparation.
Instead of preparation-section in the first drawing, the instructions will be displayed at this place.
Please notice the second image.

**Comment by gregorsart** [comment]
One little thing I noticed. You write: "Link-Component (visible as button), that redirects to starting page".

Maybe you can specify:

1. What is the Starting Page
2. What will the `href` be or will it be a `Router.back()`

Apart from that, I understood everything. The wireframes are nice, too.

**Comment by gwittm** [comment]
Thank you :)

**Comment by NikRoe** [comment]
Hi there,

with the updates it looks good to me and your comment serves as a great addition / extension for the previous description of the US.

> Hi All, we just noticed that we forgot to mention one section. The following sections will be displayed in the overview section: type, preparation time, amount of servings, preparation. Instead of preparation-section in the first drawing, the instructions will be displayed at this place. Please notice the second image.

For upcoming reviews it would be amazing, @gregorsart, if you could also leave a reaction is slack, so that people know the current status of the Review =)
