### ISSUE TITLE
US4-DeleteRecipe

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#15]
## Value proposition
As a user
I want to delete recipes
In order to remove unneeded recipes.

## Description
![Bildschirm­foto 2023-10-26 um 11 18 33](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/1f9faa4f-8465-451c-982d-6a74de29b491)

## Acceptance criteria
- [ ] a Button "Delete Recipe" is displayed at every details page 
- [ ] When clicking the button a pop up will be opened
- [ ] Pop up asks me if i really want to delete my recipe
- [ ] two buttons at pop up: yes and no
- [ ] Clicking  "no" closes the pop up and leads user back to details page
- [ ] Clicking "yes" deletes the recipe and redirects user to overview page

## Tasks
- [ ] create new branch "US4-DeleteRecipe"
- [ ] create new Component ButtonDelete
- [ ] create new Component DeletePopUp
- [ ] Pop up asks for confirmation. 
- [ ] display two buttons at pop up: yes and no
- [ ] event-listener for "yes" button
- [ ] router-push after delete recipe to overview page
- [ ] implement Delete-Method for Database
- [ ] event-listener for no-button, that closes pop up

**Comment by NikRoe** [comment]
Hi there,

this looks very nice, great work!
