### ISSUE TITLE
US7-EditRecipe

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#16]
## Value proposition
As a user
I want to edit recipes
In order to correct mistakes.

## Description
![Bildschirm­foto 2023-10-26 um 12 26 36](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/69e6395d-4d75-44ec-b6c1-cdfaf0be974d)

## Acceptance criteria
- [x] at every details page a button "edit recipe" is displayed
- [x] clicking the button leads to "AddRecipe Formular"
- [x] the heading displays the title of the recipe
- [x] all input-fields are prefilled with origin text/number...
- [x] all fields can be edited
- [x] Button "Delete changes" at bottom of the formular leads back to details page without changes
- [x] Button "Save changes" at bottom of the formular saves changes and leads to updated details page

## Tasks
- [x] New branch "US7-EditRecipe"
- [x] create Component "EditButton", that is displayed at every details page
- [x] Edit-Button leads to formular "AddNewRecipe"
- [x] change Formular to have a dynamic heading: "Add Recipe" when using it for adding a new recipe
and a specific title when editing an existing recipe
- [x] Implement PUT-Method for DataBase
- [x] create Link Component "Delete Changes", that redirects back to details page 
- [x] create button "Save changes", that updates recipe at DataBase and redirects to details page

**Comment by NikRoe** [comment]
Hi there,

well done 🙌
