### ISSUE TITLE
US2 - Add Formular for new Recipe

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#3]
## Value proposition
As a user 
I want to add new recipes 
In order to store and to find them at any time.

## Description
<img width="306" alt="Bildschirm­foto 2023-10-17 um 10 15 27" src="https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/06683015-9556-4adc-b9bd-534e17106d0b">

## Acceptance criteria
- [ ] Formular for adding new recipes
- [ ] Heading 
- [ ] Input-Field Title
- [ ] Input-Field "Prepared with" Dropdown with values microwave, oven, stove
- [ ] Input-Field Type with several values 
- [ ] Input-Field Time (Number)
- [ ] Input-Field Preparation (Text)
- [ ] Submit-Button 
- [ ] New Recipe is stored in Database

## Tasks
- [ ] new branch "US2-FormularRecipe"
- [ ] Component FormularAddRecipe
- [ ] Heading "new Recipe"
- [ ] Add Input-Fields and Labels according to Aria
- [ ] Add Submit-Button with event-listener
- [ ] POST-Method

**Comment by NikRoe** [comment]
Hi there,

this looks very promising!

For the Acceptance Criteria I have two questions:

- are all fields mandatory or could a user leave some fields empty?
- will the user stay on the form page after adding a new recipe or will they be redirected somewhere? 

Once you have answered those questions for yourselves, you can add those two things two the ACs.

Apart form that, all looks good to me.

Keep it up 🙌

**Comment by NikRoe** [comment]
LGTM
