### ISSUE TITLE
US9- Shopping List

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#30]
## Value proposition
As a user 
I want to add ingredients to a Shopping List
In order to have a list of what i need to buy.

## Acceptance criteria
- [ ] a Link at the NavBar that leads to a Shopping List
- [ ] a checkbox next to each ingredient at the recipes detail pages
- [ ] clicking the checkbox adds the ingredient to the shopping list (sets a hook)
- [ ] clicking it again removes the ingredient from the shopping list and also removes the hook
- [ ] all added ingredients are listed at the Shopping List 

## Tasks
- [ ] new branch
- [ ] create page Shopping List
- [ ] Add Link to Shopping List at starting page
- [ ] add checkbox next to each ingredient at detail pages
- [ ] add toggle-function to ingredients
- [ ] useState for added and removed 
- [ ] display added ingredients at Shopping List
