### ISSUE TITLE
US10- Basic Search Function

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#32]
## Value proposition
As a user
I want to have a search bar
In order to quickly find what I´m looking for.
## Description
![Bildschirm­foto 2023-11-14 um 13 06 53](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/b063a404-4969-4596-b3c5-fa3d628e1ef4)

## Acceptance criteria
- [ ] Search-Bar at Starting-Page
- [ ] When typing, all results are shown underneath
- [ ] Results are shown in a container (new color)
- [ ] Opacity of main page in the background will be changed
- [ ] Results can be clicked and lead to details page

## Tasks
- [ ] create new branch
- [ ] create new component SearchBar
- [ ] render Component at Starting Page
- [ ] create label and input-Field 
- [ ] create handle-Function on event
- [ ] filter-function for fetched recipes (title)
- [ ] create titles as links to detail page

**Comment by maryhbb** [comment]
LGTM ✅
