### ISSUE TITLE
US10- Basic Header

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#37]
## Value proposition
As a user
I want to have a header at each page
In order to see which app i am currently using. 

## Description
![Bildschirm­foto 2023-11-17 um 09 23 54](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/d75b9f43-defc-4654-8a90-fb95bcefd19e)

## Acceptance criteria
- [ ] Header at each page
- [ ] displays "digital recipe book"
- [ ] font-size gets smaller when display size gets smaller

## Tasks
- [ ] new branch
- [ ] new Header-Component
- [ ] render Header at _app.js
- [ ] Header styling dynamic size

**Comment by vlatkojuric** [comment]
Hello, great idea ,super simple as it should be, only thing I would suggest is to make a more detailed wireframe : 
- display the digital recipe book in the wireframe.
Otherwise everything looks good ,nice job.

**Comment by gwittm** [comment]
Hi! Thanks for your comment. The app has already some User-Storys including several content-pages... In this case we think it is enough to just focus on the header?
