### ISSUE TITLE
US11- Icons

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#41]
## Value proposition
As a user
I want to see self-explanatory icons instead of long texts
In order to improve the accessibility of the app.

## Description
replace texts on buttons by suitable icons

## Acceptance criteria
- [ ] Icon instead of "x"
- [ ] Icon instead of "edit"
- [ ] Icon instead of "submit"
- [ ] Icon instead of "back"
- [ ] Icon instead of "no"
- [ ] Icon instead of "yes"
- [ ] Icon instead of "+"
- [ ] All buttons work as before 

## Tasks
- [ ] Search and implement suitable icons
