### ISSUE TITLE
US13-Basic Shopping List

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#46]
## Value proposition
As a  user
I want to put all needed items to a shopping list
In order to have an overview of what i need to buy.
## Description
![Bildschirm­foto 2023-11-28 um 11 18 55](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/7d458788-2da1-44b3-9e06-e71ad6ae3a82)

## Acceptance criteria
- [ ] a new page "Shopping List"
- [ ] Link at NavBar, that redirects to Shopping List
- [ ] A formular at Shopping List, where i can add an item and if needed an amount and the unit
- [ ] a Submit-Button (+), that displays the item at a Container underneath the formular
- [ ] when clicking the Button, all input-fields are resetted and the focus is set to the first input-field 
- [ ] x-Button is displayed next to each item.
- [ ] clicking the x-Button deletes the item from the list

## Tasks
- [ ] new Branch "Basic Shopping List"
- [ ] new Component "Shopping List"
- [ ] render Component "FormularIngredients" to the Shopping List (useState)
- [ ] display added items the same way as in FormularAddRecipe/ FormularIngredients

**Comment by BirkBee** [comment]
LGTM 👍
