### ISSUE TITLE
US13- Shopping List with items from recipe

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#47]
## Value proposition
As a user
I want to easily add ingredients from my recipes to the shopping list
In order to have an overview of what i need to buy.
## Description
![Bildschirm­foto 2023-11-28 um 11 31 56](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/fde5945e-0cbe-426f-9b94-642c6ca4dfb4)

## Acceptance criteria
- [ ] at the detailpage, each ingredient is displayed with a checkbox next to it
- [ ] clicking the checkbox sets a hook
- [ ] as soon as a hook is set, the ingredient is added to the shoppingList
- [ ] clicking again removes the hook and the item from the shoppingList

## Tasks
- [ ] new branch
- [ ] add checkbox next to each li-item (ingredients)
- [ ] add toggle-function, that adds and removes item to and from shoppingList when clicked
- [ ] add and remove hook at checkbox when toggling
