### ISSUE TITLE
US14 - add toggle-function at ShoppingList

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#48]
## Value proposition
As a user
I want to set a hook to all items at the shopping list
In order to update my list while being e.g. in the store.
## Description
![Bildschirm­foto 2023-11-28 um 11 38 55](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/c77673fa-efca-49ac-8e3d-b36079e72d9f)

## Acceptance criteria
- [ ] All items at the shopping list are displayed with a checkbox
- [ ] clicking the checkbox sets and removes a hook 

## Tasks
- [ ] add checkbox to List-Elements at shopping-list
- [ ] add toggle-function
