### ISSUE TITLE
US12 - FavoritePage

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#49]
## Value proposition
As a user
I want to add recipes to a favorite page
In order to quickly find them again.
## Description
![Bildschirm­foto 2023-11-28 um 12 21 57](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/f0a5520a-81a2-4a49-b99d-706444554957)

## Acceptance criteria
- [ ] a new Page: FavoriteRecipesPage
- [ ] Link at NavBar, that redirects to FavoriteRecipesPage 
- [ ] Link at NavBar is a Button, that is displayed as an icon
- [ ] Favorite-Button is displayed at overviewPage and at detailsPage
- [ ] clicking the Favorite-Button adds and removes recipe to and from FavoriteRecipesPage
- [ ] at the same time the background of the displayed picture changes 
## Tasks
- [ ] new branch
- [ ] new component "FavoriteButton"
- [ ] render component at detailsPage and OverviewPage
- [ ] add toggle-function
- [ ] create new page, that renders all Recipes that are favorite in a list, same as at overview page

**Comment by Philipp-Hess** [comment]
Hi team, great work! 👍 I only have one suggestion: maybe you'd want to consider giving the user some feedback, like a little notification in a popup, when they add a recipe to the FavoriteRecipesPage. Something simple like 'Recipe added to favorites! 😋' would enhance the user experience. Keep up the good work!
