### ISSUE TITLE
Design

### ISSUE THREAD

**Issue by gwittm** [gwittm/Digital-Recipe-Book#57]
## Value proposition
As a user 
I want to have an attractive looking app with an intuitive and clear design
In order to enjoy using it on a screen of 375 x 667px.

## Description
![Bildschirm­foto 2023-12-15 um 19 57 16](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/1e1ecc3f-a3df-41cb-9bdd-f7bbd750e5c6)
![Bildschirm­foto 2023-12-15 um 19 57 45](https://github.com/gwittm/Digital-Recipe-Book/assets/128288586/eaafbef8-a83c-4d81-9881-bd25e0aee709)

## Acceptance criteria
- [ ] Root colors are set and used
- [ ] Hover-Effects at Buttons and Links 
- [ ] Suitable Images are set as Banner Image at Main Page and Favorite Page
- [ ] Suitable Images are set on top at the Add- and Edit-Form-Page
- [ ] Minimalistic FuseSearch-Bar at Main Page
- [ ] All Recipes at Main and Favorite-Page are visible as Links (hover-Effect) with Image and positioned Favorite Button 
- [ ] Details Page has a well structured and attractive design
- [ ] Formular has a well structured design and can be used intuitively 
- [ ] Margin and Padding-Values are set equalily to achieve a uniform and clear appearance
- [ ] All Border-Radius-Values are set equally
- [ ] Folder-Structure is clear and Styled Components are separated from Functions

## Tasks
- [ ] search for suitable root-colors
- [ ] search for suitable images
- [ ] design pages with flex-boxes, margin and Padding-Values...
- [ ] outsourcing of  Styled Components
